version: "3.8"
services:
  client:
    image: node:12-alpine
    build:
      context: ./packages/hearthstone-client
      dockerfile: Dockerfile
    env_file:
      - .env
    command: npm run client
    volumes:
      - ./packages/hearthstone-client:/packages/hearthstone-client:delegated
      - node_modules:/packages/hearthstone-client/node_modules
    working_dir: /usr/src/app/packages/hearthstone-client
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - server
  server:
    image: node:12-alpine
    build:
      context: ./packages/hearthstone-server
      dockerfile: Dockerfile
    env_file:
      - .env
    command: npm run server
    volumes:
      - ./packages/hearthstone-server:/packages/hearthstone-server:delegated
      - node_modules:/packages/hearthstone-server/node_modules
    working_dir: /usr/src/app/packages/hearthstone-server
    ports:
      - 4000:4000

volumes:
  node_modules:
